config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "about" => "pages#about"

  authenticated :user do
    root to: "statuses#index"
  end

  unauthenticated :user do
    root to: "pages#home", as: :unauthenticated_root
  end

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/status.rb
class Status < ApplicationRecord
  def posted?
    self.done == true
  end

  def failed?
    self.failed == true
  end

  after_save_commit do
    if starts_previously_changed?
      UpdateStatusJob.set(wait_until: self.starts).perform_later(self)
    end
    if expires_previously_changed?
      ClearStatusJob.set(wait_until: self.expires).perform_later(self)
    end
  end

  GITLAB_API_URL = "https://gitlab.com/api/v4/user/status"

  def clear_status
    conn = Faraday.new(
      url: GITLAB_API_URL,
      params: {},
      headers: {'PRIVATE-TOKEN' => User.find_by(id: self.created_by).personal_access_token}
    )
    conn.put()
  end

  def patch_status
    conn = Faraday.new(
      url: GITLAB_API_URL,
      params: {
        message: self.text,
        emoji: self.emoji,
        availability: self.busy ? "busy" : "available",
      },
      headers: {'PRIVATE-TOKEN' => User.find_by(id: self.created_by).personal_access_token, 'Content-Type': 'application/json' }
    )
    conn.put()
  end

  def api_call!
    begin
      response = patch_status
    rescue Faraday::Error => e
      # You can handle errors here (4xx/5xx responses, timeouts, etc.)
      puts e.response[:status]
      puts e.response[:body]
    end
    success = response.success?
    update(done: response.success?)
    update(failed: !response.success?)
  end

  validates :expires, :allow_blank => true, comparison: { greater_than: :starts, message: "must be after start" }
  validates_length_of :text, maximum: 100
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  around_action :set_time_zone, if: :current_user

  private

  def set_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
  def about
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
    # Don't allow editing posted statuses
    if @status.posted?
      redirect_to status_url(@status), alert: "Can't edit posted statuses"
    end
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params) do |s|
      s.created_by = current_user.id
    end
    if @status.save
      UpdateStatusJob.set(wait_until: @status.starts).perform_later(@status)
      ClearStatusJob.set(wait_until: @status.expires).perform_later(@status)
    end

    respond_to do |format|
      if @status.save
        format.html { redirect_to status_url(@status), notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to status_url(@status), notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy!

    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:text, :busy, :emoji, :starts, :expires, :created_b, :failed)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:time_zone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:personal_access_token, :time_zone])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date_time(date_time)
    date_time.in_time_zone(current_user.time_zone).strftime("%F %l:%M %p")
  end

  ONE_MINUTE = (1.0/24/60)
  
  def one_minute_from_now_datetime
    DateTime.current + ONE_MINUTE
  end
  def one_minute_from_now_date
    Date.current + ONE_MINUTE
  end

  def get_emoji_by_name(name)
    result = Emoji.find_by_alias(name)
    result.raw if result
  end

  def get_current_status()
    JSON.parse Faraday.new(
      url: "https://gitlab.com/api/v4/user/status",
      params: {},
      headers: {'PRIVATE-TOKEN' => current_user.personal_access_token}
    ).get().body
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitLab Status Minder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="Schedule your GitLab statuses">
    <meta property="og:image" content="<%= image_url('seo.png') %>" />
    <meta property="og:description" content="Schedule your GitLab statuses" />
    <meta property="og:title" content="GitLab Status Minder" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Schedule your GitLab statuses" />
    <meta name="twitter:image" content="<%= image_url('seo.png') %>" />
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-default antialiased">
    <div class="sticky z-10 bg-default top-0 flex gap-2 p-2 sm:items-center justify-between border-b dark:border-gray-800 h-12">
      <%= link_to :root, class:"link text-inherit rounded ring-offset-4" do %>
        <div class="flex gap-2 items-center">
          <%= image_tag "logo.png", class: " w-7 h-7", alt: "" %>
          <span class="text-lg font-semibold">
            GitLab Status Minder
          </span>
        </div>
      <% end %>
      <div class="flex gap-2 sm:items-center flex-col sm:flex-row sm:justify-end">
        <% if user_signed_in? %>
          <div data-controller="menu" class="relative">
            <div data-action="click->menu#toggle" class="flex items-center">                                                                                                                                           
              <button data-menu-target="button" type="button" class="p-2 border border-transparent hover:border-inherit button m-0" 
        id="options-menu" aria-haspopup="true" aria-expanded="true">
                <svg viewBox="0 0 100 80" class="w-3 h-3 fill-current">
                  <rect width="100" height="10" rx="8"></rect>
                  <rect y="30" width="100" height="10" rx="8"></rect>
                  <rect y="60" width="100" height="10" rx="8"></rect>
                </svg>
              </button>
            </div>
            <div data-menu-target="toggleable" class="z-10 absolute right-0 hidden mt-1 bg-default w-max max-w-96 origin-top-right rounded ring-1 ring-black dark:ring-white ring-opacity-5 max-sm:-right-2 max-sm:w-screen max-sm:max-w-none max-sm:rounded-none max-sm:h-[calc(100vh-48px)] max-sm:ring-0 max-sm:border-t max-sm:mt-2">
              <div class="py-3 px-4 text-gray-500 dark:text-gray-400 border-b break-all">
                <%= current_user.email %>
              </div>
              <div class="flex flex-col" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                <%= link_to "Edit profile", edit_user_registration_path, class: "py-3 px-4 hover:bg-purple-50 dark:hover:bg-purple-950 hover:text-purple-600 dark:hover:text-purple-200 focus:text-purple-600 focus:outline-none focus:ring focus:ring-inset focus:ring-purple-600" %>
                <%= link_to "About", about_path, class: "py-3 px-4 hover:bg-purple-50 dark:hover:bg-purple-950 hover:text-purple-600 dark:hover:text-purple-200 focus:text-purple-600 focus:outline-none focus:ring focus:ring-inset focus:ring-purple-600" %>
                <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "py-3 px-4 hover:bg-red-50 dark:hover:bg-red-950 focus:outline-none focus:ring focus:ring-inset focus:ring-red-600 text-red-600 dark:text-red-200"  %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user && current_user.personal_access_token.present? %>
    <%= render "statuses/current_status" %>
  <% end %>
  <main class="container mx-auto mt-5 px-5 flex flex-col">
    <% if notice %>
      <div class="alert success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert danger"><%= alert %></div>
    <% end %>
    <%= yield %>
  </main>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitLab Status Minder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="Schedule your GitLab statuses">
    <meta property="og:image" content="<%= image_url('seo.png') %>" />
    <meta property="og:description" content="Schedule your GitLab statuses" />
    <meta property="og:title" content="GitLab Status Minder" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Schedule your GitLab statuses" />
    <meta name="twitter:image" content="<%= image_url('seo.png') %>" />
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-default antialiased">
    <main class="container mx-auto mt-5 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="my-4 mx-auto max-w-5xl">
  <%= link_to :root do %>
    <h1 class="text-7xl font-bold gradient-text mb-12 max-sm:flex lg:inline-flex items-center max-sm:flex-col max-sm:items-start gap-4">
      <%= image_tag "logo.png", class: "w-16 h-16 inline", alt: "" %>
      GitLab Status Minder
    </h1>
  <% end %>
  <div class="">
    <div class="my-12">
      <h2 class="text-2xl max-sm:text-3xl font-semibold gradient-text mb-2">What is this?</h2>
      <p class="leading-tight max-sm:text-xl">
        GitLab Status Minder is a small, open-source app for scheduling GitLab user statuses.
      </p>
    </div>
    <div class="my-12">
      <h2 class="text-2xl max-sm:text-3xl font-semibold gradient-text mb-2">How does it work?</h2>
      <p class="leading-tight max-sm:text-xl">
        Create an account, add a <a target="_blank" class="link" href="https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html">GitLab Personal Access Token</a>, and start scheduling statuses to keep your teammates updated about your availability.
      </p>
    </div>
    <div class="my-12">
      <h2 id="setup" class="text-2xl max-sm:text-3xl font-semibold gradient-text mb-2">How do I set up my account?</h2>
      <ol class="list-decimal pl-5 my-4">
        <li>Create a <a target="_blank" class="link" href="https://gitlab.com/-/user_settings/personal_access_tokens">GitLab Personal Access Token</a> with the <code class="code">api</code> scope. </li>
        <li>Add your PAT to <%= link_to "your profile", edit_user_registration_path, class: "link", target: "_blank" %> and make sure you've set your Time zone.</li>
      </ol>
    </div>
  </div>
  <% if !user_signed_in? %>
    <div class="flex gap-2 flex-col sm:flex-row">
      <%= link_to "Sign up", new_user_registration_path, class: "button primary m-0 text-center" %>
      <%= link_to "Login", new_user_session_path, class: "button m-0 text-center" %>
    </div>
  <% end %>
  <div class="fixed bottom-0 left-0 right-0 p-4 flex justify-end bg-default items-center gap-2 max-sm:static max-sm:px-0">
    <a class="link inline-block" href="https://gitlab.com/chadlavimoniere/gitlab-status-minder" target="_blank">
      <div class="flex justify-end bg-default items-center gap-2 text-inherit text-sm">
        <svg class="w-[1em] h-[1em]" xmlns="http://www.w3.org/2000/svg" viewBox="80 80 220 220"><g id="gitlab-logo"><path class="fill-current" d="M282.83,170.73l-.27-.69-26.14-68.22a6.81,6.81,0,0,0-2.69-3.24,7,7,0,0,0-8,.43,7,7,0,0,0-2.32,3.52l-17.65,54H154.29l-17.65-54A6.86,6.86,0,0,0,134.32,99a7,7,0,0,0-8-.43,6.87,6.87,0,0,0-2.69,3.24L97.44,170l-.26.69a48.54,48.54,0,0,0,16.1,56.1l.09.07.24.17,39.82,29.82,19.7,14.91,12,9.06a8.07,8.07,0,0,0,9.76,0l12-9.06,19.7-14.91,40.06-30,.1-.08A48.56,48.56,0,0,0,282.83,170.73Z"/></g></svg>
        View source
      </div>
    </a>
    <div>
    </div>

app/views/pages/home.html.erb
<div class="mt-4 mb-20 mx-auto max-w-5xl">
  <h1 class="text-7xl font-bold gradient-text mb-12 max-sm:flex lg:inline-flex items-center max-sm:flex-col max-sm:items-start gap-4">
    <%= image_tag "logo.png", class: "w-16 h-16 inline", alt: "" %>
    GitLab Status Minder
  </h1>
  <div class="sm:flex gap-6">
    <div class="my-12 basis-1/2 sm:home-card max-sm:text-lg">
      <h2 class="text-2xl max-sm:text-3xl font-semibold gradient-text mb-2">What is this?</h2>
      <p class="leading-tight">
        GitLab Status Minder is a small, open-source app for scheduling GitLab user statuses.
      </p>
    </div>
    <div class="my-12 basis-1/2 sm:home-card max-sm:text-lg">
      <h2 class="text-2xl max-sm:text-3xl font-semibold gradient-text mb-2">How does it work?</h2>
      <p class="leading-tight">
        Create an account, add a <a target="_blank" class="link" href="https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html">GitLab Personal Access Token</a>, and start scheduling statuses to keep your teammates updated about your availability.
      </p>
    </div>
  </div>
  <div class="flex gap-2 flex-col sm:flex-row">
    <%= link_to "Sign up", new_user_registration_path, class: "button primary m-0 text-center" %>
    <%= link_to "Login", new_user_session_path, class: "button m-0 text-center" %>
  </div>
  <div class="fixed bottom-0 left-0 right-0 p-4 flex justify-end bg-default items-center gap-2 max-sm:static max-sm:px-0">
    <a class="link inline-block" href="https://gitlab.com/chadlavimoniere/gitlab-status-minder" target="_blank">
      <div class="flex justify-end bg-default items-center gap-2 text-inherit text-sm">
        <svg class="w-[1em] h-[1em]" xmlns="http://www.w3.org/2000/svg" viewBox="80 80 220 220"><g id="gitlab-logo"><path class="fill-current" d="M282.83,170.73l-.27-.69-26.14-68.22a6.81,6.81,0,0,0-2.69-3.24,7,7,0,0,0-8,.43,7,7,0,0,0-2.32,3.52l-17.65,54H154.29l-17.65-54A6.86,6.86,0,0,0,134.32,99a7,7,0,0,0-8-.43,6.87,6.87,0,0,0-2.69,3.24L97.44,170l-.26.69a48.54,48.54,0,0,0,16.1,56.1l.09.07.24.17,39.82,29.82,19.7,14.91,12,9.06a8.07,8.07,0,0,0,9.76,0l12-9.06,19.7-14.91,40.06-30,.1-.08A48.56,48.56,0,0,0,282.83,170.73Z"/></g></svg>
        View source
      </div>
    </a>
    <div>
    </div>

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% status.text = params[:text] unless status.text %>
  <% status.busy = params[:busy] unless status.busy %>
  <% status.emoji = params[:emoji] unless status.emoji %>
  <% if status.errors.any? %>
    <div class="alert danger">
      <h2><%= pluralize(status.errors.count, "error") %> prevented this status from being saved:</h2>
      <ul class="list-disc pl-4">
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-4 w-full" data-controller="countchar">
    <%= form.label :text, 'Status', class: "input-label" %>
    <%= form.text_field :text, required: true, autofocus: true, class: "input", data: { countchar_target: 'name', action: 'keyup->countchar#countCharacters' } %>
    <div class="text-sm opacity-90 mt-1" data-countchar-target='wrapper'>
      Characters: <span data-countchar-target='counter'><%= status.text.to_s.length %></span>/100
    </div>
  </div>
  <div class="my-4 w-full flex gap-4 flex-col sm:flex-wrap">
    <div class="flex gap-4 flex-grow flex-col sm:flex-row">
      <div class="flex-grow">
        <%= form.label :starts, class: "input-label" %>
        <!-- Default start time to one minute in the future if it doesn't exist -->
        <%= form.datetime_field :starts, class: "input", :value => status.starts || one_minute_from_now_datetime, min: DateTime.current, required: true, include_seconds: false %>
      </div>
      <div class="flex-grow">
        <%= form.label :expires, 'Expires (optional)', class: "input-label" %>
        <%= form.datetime_field :expires, class: "input", min: status.starts || one_minute_from_now_date %>
      </div>
    </div>
    <div class="flex gap-4 items-center max-sm:flex-col max-sm:items-start">
      <div class="flex gap-1.5 items-center input-label mb-0">
        <%= form.check_box :busy, class: "checkbox" %>
        <%= form.label :busy %>
      </div>
      <noscript>
        <div class="max-md:w-full">
          <%= form.label :emoji, 'Emoji (optional)', class: "input-label" %>
          <%= form.select :emoji, [['None', nil], *EMOJIS], {}, class: "input" %>
        </div>
      </noscript>
      <div class="flex">
        <button type="button" id="emoji-picker-trigger" class="button p-2 m-0 flex justify-center items-center gap-2" title="Edit emoji">
          <span id="emoji-display" class="font-emoji h-5"><%= get_emoji_by_name(status.emoji) || get_emoji_by_name("slightly_smiling_face") %></span>
          <pre id="emoji-display-name" class="font-mono text-sm"><%= status.emoji.present? ? ":" + status.emoji + ":"  : "Add emoji" %></pre>
        </button>
        <%= form.text_field :emoji, class: "hidden", id: "emoji-input" %>
      </div>
    </div>
  </div>
  <div class="mt-5 w-full flex gap-2">
    <%= form.submit 'Save', :class => "button primary" %>
    <%= link_to "Cancel", statuses_path, class: "button" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="inline">
  <%= link_to statuses_path, class: "link text-sm inline-flex items-center gap-1" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="w-[0.85em] h-[0.85em]" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
    </svg>
    <span>Back to statuses</span>
  <% end %>
</div>
<h1 class="h1">Edit status</h1>
<%= render "form", status: @status %>

app/views/statuses/index.html.erb
<% user_statuses = @statuses.filter{ |s| s.created_by == current_user.id }.sort_by(&:starts) %>
<% filtered_statuses = user_statuses.filter{ |s| !s.done } %>
<% done_statuses = user_statuses.filter{ |s| s.done }.reverse %>
<% if current_user.personal_access_token.present? %>
  <h1 class="h1 mb-4">Scheduled statuses</h1>
  <% unless filtered_statuses.empty? %>
    <ul id="statuses">
      <% filtered_statuses.each do |status| %>
        <li class="status list-none mb-3 last:mb-0 rounded-lg border dark:border-gray-500 <%= status.failed? ? 'border-red-600 bg-red-50 dark:bg-red-950 dark:border-red-400 dark:bg-opacity-50' : '' %>">
          <%= link_to status, class: 'rounded' do %>
            <div class="p-3">
              <%= render status %>
            </div>
          <% end %>
        </li>
      <% end %>
      <li class="status list-none mb-3 last:mb-0 flex">
        <%= link_to "Add status", new_status_path, class: "button primary" %>
      </li>
    </ul>
  <% else %>
    <div class="flex">
      <%= link_to "Add status", new_status_path, class: "button primary" %>
    </div>
  <% end %>
  <% if done_statuses.any? %>
    <details>
      <summary class="h1 my-4 cursor-pointer">
        Posted statuses (<%= done_statuses.length %>)
      </summary>
      <ul id="past-statuses">
        <% done_statuses.each do |status| %>
          <li class="status list-none mb-3 last:mb-0 rounded-lg border dark:border-gray-500">
            <%= link_to status, class: 'rounded' do %>
              <div class="p-3">
                <%= render status %>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </details>
  <% end %>
<% else %>
  <div class="w-screen h-screen fixed left-0 right-0 top-12 bottom-0 bg-gray-950 bg-opacity-30 flex items-center justify-center">
    <div class="p-6 rounded-lg bg-blue-50 dark:bg-blue-950 max-w-prose">
      <h1 class="h1 mb-4">Let's get started</h1>
      <p class="my-4">
        This is a lightweight app for scheduling future GitLab user statuses. It uses <a href="https://docs.gitlab.com/ee/api/users.html#user-status" class="link" target="_blank">GitLab's API</a> to set your status at the desired time and clear it at the desired time.
      </p>
      <p class="my-4">
        To use this app, you need to add your <a class="link" target="_blank" href="https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html">GitLab Personal Access token</a> to your <%= link_to "profile", edit_user_registration_path, class: "link" %>. Be sure to also update your time zone if you did not set it when registering.
      </p>
      <div class="flex justify-end">
        <%= link_to "Edit profile", edit_user_registration_path, class: "button primary m-0" %>
      </div>
      <div>
      </div>
    <% end %>

app/views/statuses/new.html.erb
<div class="inline">
  <%= link_to statuses_path, class: "link text-sm inline-flex items-center gap-1" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="w-[0.85em] h-[0.85em]" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
    </svg>
    <span>Back to statuses
    </span>
  <% end %>
</div>
<h1 class="h1">New status</h1>
<%= render "form", status: @status %>

app/views/statuses/show.html.erb
<div class="inline">
  <%= link_to statuses_path, class: "link text-sm inline-flex items-center gap-1" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="w-[0.85em] h-[0.85em]" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
    </svg>
    <span>Back to statuses
    </span>
  <% end %>
</div>
<h1 class="sr-only"><%= @status.text %></h1>
<%= render @status %>
<div class="flex gap-2 mt-5">
  <% unless @status.posted? %>
    <%= link_to "Edit", edit_status_path(@status), class: "button" %>
  <% end %>
  <%= link_to @status.posted? ? "Repost" : "Duplicate", new_status_path(:text => @status.text, :busy => @status.busy, :emoji => @status.emoji), class: "button" %>
  <%= button_to "Delete", @status, method: :delete, class: "button destructive" %>
</div>